### ISSUE TITLE
"Connection: close" not handled properly

### ISSUE THREAD

**Issue by guyeeba** [zevenet/zproxy#6]
Receiving an HTTP response with "Connection: close" header and FIN flag set in the TCP packet causes inconsitent behavior, and data loss.

Sometimes the flow between zproxy and the backend is smooth, the request is sent to the backend, it sends the response that contains the "Connection: close" header and FIN flag set in the last packet, zproxy sends back FIN/ACK, and the response gets delievered to the client socket. This is what we see in in wireshark in these cases:

![image](https://user-images.githubusercontent.com/16527859/99147823-3a43ea00-2684-11eb-83d1-26f0c7944bfc.png)

But in some cases (I wasn't able to identify the reason, but it's more than 70% of all requests of this kind in our enviromnent) zproxy sends an RST packet, throws a "Remote backend host  closed connection prematurely" entry into the logs, and closes the client side of the connection without sending some or all of the received data to the client; resulting in data loss.

This is how it looks like in Wireshark:

![image](https://user-images.githubusercontent.com/16527859/99147982-63b14580-2685-11eb-891c-5b5488414cd3.png)

In my understanding, closing an HTTP connection with "Connection: close" header set is the expected behavior, and zproxy should treat it as such, and forward all the received data to the client socket before closing it.

The packet dumps are available, I can send them in a private channel upon request.

Edit: zproxy version: 0.2.4-5.11.2 from repo

Edit2: the same clients and backends work perfectly with ZLB 4.0.5

**Comment by abdessamad-zevenet** [comment]
Hi, thank you for reporting the issue.

From zproxy perspective, closing the connection uppon connection close header is expected, in this case zproxy need to wait for the backend to close its peer socket and after it closes his and it doesn't (it shouldn't) close the client side until all buffered data is forwarded to the client, this should always be the behavior .

Please do the following in order to generate debug data in order to check the issue:
Stop the affected farm, clear the syslog ( command:  _> /var/log/syslog_ ), go to the affected farm configuration file and enable debug log level changing LogLevel parameter to value 8, then start the farm.

Now using tcpdump, from the load balancer capture everything to and form zproxy using the VIP and backend addresses of the affected farm.
Reproduce the issue and create a supportsave file, which can be create within System tab in WebGUI interface

Send the pcap file and supportsave to ce-support@zevenet.com indicating this issue url, 
Let me know if you need further assistance

Thanks for your time,

**Comment by abdessamad-zevenet** [comment]
Hi, could you check the above message about the requested data needed in order to investigate this issue.

**Comment by guyeeba** [comment]
Hi, email sent, sorry for the delay...

**Comment by cano-devel** [comment]
Is this solved with the latest zproxy version?
