### ISSUE TITLE
zproxy is support  anti ddos ?

### ISSUE THREAD

**Issue by w796933** [zevenet/zproxy#8]
zproxy is support  anti ddos ?

**Comment by alvarocano-zevenet** [comment]
Hello @w796933 

zproxy doesn't have any native DDOS protection, but it supports libmodsecurity.

You only have to compile it with the **ENABLE_WAF** flag and add the rulesets using the **WafRules** directives.

In order to create the rulesets, please, check the [OWASP CRS protect](https://github.com/coreruleset/coreruleset) to get community solutions or you can create yourself rules if you know the [libmodsec project](https://github.com/SpiderLabs/ModSecurity).

Best regards
